In [ ]:
import numpy as np
import torch
import torchvision
from PIL import Image
from torch import nn
from torch.nn import functional as F
from torch.utils import data
from torchvision import transforms

Difference between Numpy array and Tensors?

Numpy array does not support GPU computation while Tensors do. Tensor class also supports automatic differentiation. 

# Math and Numerical Computing tools

In [8]:
x=torch.arange(12, dtype=torch.float32)
print(x)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])


In [9]:
x.shape

torch.Size([12])

In [11]:
# product of shape elements = size
x.numel()

12

In [13]:
x.reshape(3,4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [14]:
# We use -1 to infer the dimension which we don't want to mention. We can only mention one dimension for reshaping.
x.reshape(-1,4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [25]:
y = torch.ones(3,4)
z = torch.randn(3,4)
torch.zeros(2,3)
print(z)
# Each element is randomly sampled from a standard Gaussian (normal) distribution with mean of 0 and standard deviation of 1.

tensor([[-1.4577, -0.1835,  0.8727,  0.2685],
        [ 0.9325,  0.4865,  0.5609,  0.1360],
        [-0.9898, -0.6708, -0.2339,  0.1831]])


In [23]:
# A binary scalar operator takes two real inputs and yields on output by the signature f : R, R → R
print(torch.concat((z,y), dim=1)) # Add data as new columns
print(torch.concat((z,y), dim=0)) # Add data as new rows

tensor([[ 0.6365, -0.3415,  0.9114, -0.7631,  1.0000,  1.0000,  1.0000,  1.0000],
        [-0.3760, -0.5320, -0.3938, -0.3913,  1.0000,  1.0000,  1.0000,  1.0000],
        [ 0.9139,  0.3775,  0.5525,  0.5932,  1.0000,  1.0000,  1.0000,  1.0000]])
tensor([[ 0.6365, -0.3415,  0.9114, -0.7631],
        [-0.3760, -0.5320, -0.3938, -0.3913],
        [ 0.9139,  0.3775,  0.5525,  0.5932],
        [ 1.0000,  1.0000,  1.0000,  1.0000],
        [ 1.0000,  1.0000,  1.0000,  1.0000],
        [ 1.0000,  1.0000,  1.0000,  1.0000]])


In [27]:
print(z==y) # Binary tensor via logical statement
print(sum(z)) # Addition columnwise
z.sum() # Addition of all elements

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
tensor([-1.5150, -0.3678,  1.1997,  0.5877])


tensor(-0.0954)

In [29]:
# To perform element wise operations when shapes of input tensors differ, then we use broadcasting.
# Expand one or both array to get same shape. Then apply operation
a = torch.arange(3).reshape((3, 1))  # 3x1
b = torch.arange(2).reshape((1, 2))  # 1x2
print(a)
print(b)
# Expand both into 3x2 and then add
print(a+b)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


In [ ]:
# Indexing and Slicing is same