# Linear Algebra

In [2]:
import torch

In [23]:
# Dot product of two VECTORS
X=torch.randn((1,4))
Y=torch.randn((1,4))
print(X,Y)
torch.dot(X[0],Y[0])

tensor([[-1.1612, -0.1066,  0.7112, -2.0103]]) tensor([[ 0.7529, -0.9706, -0.0561,  1.1510]])


tensor(-3.1245)

In [ ]:
# When we normalize the two vectors to have a unit length, their dot product tells the cosine of the angle between them.
# When weights are positive and sum to 1, then dot product is called weighted average.

In [30]:
# Matrix Vector product
A=torch.randn((2,3), dtype=torch.float32)
x=torch.arange(3, dtype=torch.float32)
print(A)
print(x)
y = torch.mv(A,x)
print(y, y.shape)

# A=[2,3], x=[3] -----> y=[2]
# A useful transformation from 3 to 2 dimension.

tensor([[-0.2197, -0.5776,  0.1494],
        [ 0.1942, -0.7180, -1.3790]])
tensor([0., 1., 2.])
tensor([-0.2787, -3.4760]) torch.Size([2])


In [31]:
# Matrix Matrix product
A=torch.randn(3,3)
B=torch.randn(3,4)
torch.mm(A,B)

tensor([[ 3.8165,  0.5862,  2.6685, -2.8223],
        [ 0.3464, -0.7907, -0.0780,  1.9494],
        [ 2.4999, -1.1593,  3.1194,  0.7055]])